// Canonical enums matching lib/domain/enums.js

export enum VaultStatus {
  DRAFT = 'DRAFT',
  FUNDED = 'FUNDED',
  RELEASED = 'RELEASED',
  REFUNDED = 'REFUNDED',
  DISPUTED = 'DISPUTED',
  CANCELLED = 'CANCELLED',
}

export enum VaultType {
  FIXED_PRICE = 'FIXED_PRICE',
  DEVELOPMENT = 'DEVELOPMENT',
  DESIGN = 'DESIGN',
  CONTENT_AI = 'CONTENT_AI',
}

export enum VerificationResult {
  PASS = 'PASS',
  FAIL = 'FAIL',
  FLAGGED = 'FLAGGED',
  HUMAN_REVIEW = 'HUMAN_REVIEW',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  NEEDS_INFO = 'NEEDS_INFO',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
}

export enum UserRole {
  NONE = 'NONE',
  CLIENT = 'CLIENT',
  FREELANCER = 'FREELANCER',
  ADMIN = 'ADMIN',
}

export enum KycStatus {
  NONE = 'NONE',
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum InviteStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
}

export enum LedgerEntryType {
  DEPOSIT = 'DEPOSIT',
  LOCK = 'LOCK',
  RELEASE = 'RELEASE',
  REFUND = 'REFUND',
  WITHDRAW = 'WITHDRAW',
  FEE = 'FEE',
}

export enum DisputeType {
  VERIFICATION_ERROR = 'VERIFICATION_ERROR',
  REQUIREMENT_MISMATCH = 'REQUIREMENT_MISMATCH',
  SCOPE_CHANGE = 'SCOPE_CHANGE',
  BAD_FAITH = 'BAD_FAITH',
  FRAUD = 'FRAUD',
  PROCESS_BREACH = 'PROCESS_BREACH',
  SECURITY = 'SECURITY',
}

export enum EvidenceType {
  MESSAGE = 'MESSAGE',
  MESSAGE_SENT = 'MESSAGE_SENT',
  REQUIREMENT_ITEM = 'REQUIREMENT_ITEM',
  SUBMISSION_DELTA = 'SUBMISSION_DELTA',
  REVIEW_DECISION = 'REVIEW_DECISION',
  DISPUTE_NOTE = 'DISPUTE_NOTE',
  DISPUTE_EVIDENCE = 'DISPUTE_EVIDENCE',
  DISPUTE_DECISION = 'DISPUTE_DECISION',
}

export enum SubmissionType {
  FILE = 'FILE',
  LINK = 'LINK',
  BOTH = 'BOTH',
}